apiVersion: v1
kind: Namespace
metadata:
  name: poc-auth
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: client-sa
  namespace: poc-auth
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: server-sa
  namespace: poc-auth
